package services;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.google.api.services.calendar.model.Event;

import calenderapi.CalendarQuickstart;
import factory.EventFactory;
import model.Meeting;
import repositories.MeetingRepository;

@Service
public class MeetingServices {
	//CalendarQuickstart cq = new CalendarQuickstart();

	// in this service, i will create a calendar event if the meeting is inserted
	// into our db.. might want to do it
	// the other way around, where the meeting is only inserted into our db if the
	// calendar event is added to calendar
	// this method returns 0 if unsuccessful
	@Autowired
	MeetingRepository mr;
	
	public int insertMeeting(Meeting m) {
			// using an eventFactory, we can create events in the calendar from courses or
			// meetings with the same method
			// call because the method is overloaded to handle meetings and courses
			Event event = EventFactory.getEvent(m);
			//string pk for events that is generated by google..
			//event.getId()
			//could use this string ID in our tables to get matching ids!!!!
			System.out.printf("Event created: %s\n", event.getHtmlLink());
			//
			return mr.insertMeeting(m);

	}
	
	public List<Meeting> getAllMeetings(){
		return mr.selectAllMeetings();
	}
	
	public Meeting getMeetingById(int id) {
		return mr.selectMeetingById(id);
	}
	
	//need to have these affect calendar
	public void updateMeeting(Meeting change) {
		mr.updateMeeting(change);
	}
	
	//need to have these affect calendar
	public void deleteMeetingById(int id) {
		mr.deleteMeetingById(id);
	}
}
